---
- name: set erlang cookie
  template:
    src: erlang.cookie.j2
    dest: "{{ rabbitmq_erlang_cookie_file }}"
    owner: rabbitmq
    group: rabbitmq
    mode: 0400
  notify:
    - "{{ rabbitmq_restart_handler }}"
    - remove non-master-node on master

- name: flush handlers
  meta: flush_handlers
